//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarOffgridSystemDesigner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double ModuleLosses {
            get {
                return ((double)(this["ModuleLosses"]));
            }
            set {
                this["ModuleLosses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LPSecurityFactor {
            get {
                return ((double)(this["LPSecurityFactor"]));
            }
            set {
                this["LPSecurityFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Ka {
            get {
                return ((double)(this["Ka"]));
            }
            set {
                this["Ka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Kb {
            get {
                return ((double)(this["Kb"]));
            }
            set {
                this["Kb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Kc {
            get {
                return ((double)(this["Kc"]));
            }
            set {
                this["Kc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Kr {
            get {
                return ((double)(this["Kr"]));
            }
            set {
                this["Kr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Kx {
            get {
                return ((double)(this["Kx"]));
            }
            set {
                this["Kx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Daut {
            get {
                return ((double)(this["Daut"]));
            }
            set {
                this["Daut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double Pd {
            get {
                return ((double)(this["Pd"]));
            }
            set {
                this["Pd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public double Kt {
            get {
                return ((double)(this["Kt"]));
            }
            set {
                this["Kt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint Favmodule1 {
            get {
                return ((uint)(this["Favmodule1"]));
            }
            set {
                this["Favmodule1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint Favmodule2 {
            get {
                return ((uint)(this["Favmodule2"]));
            }
            set {
                this["Favmodule2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint Favmodule3 {
            get {
                return ((uint)(this["Favmodule3"]));
            }
            set {
                this["Favmodule3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint Favmodule4 {
            get {
                return ((uint)(this["Favmodule4"]));
            }
            set {
                this["Favmodule4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint Favmodule5 {
            get {
                return ((uint)(this["Favmodule5"]));
            }
            set {
                this["Favmodule5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u9hEEQj62HzHMi9wUvEWe3LxC25aAgdFfFMiwQHy")]
        public string APIKey_NREL {
            get {
                return ((string)(this["APIKey_NREL"]));
            }
            set {
                this["APIKey_NREL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint FavInverter1 {
            get {
                return ((uint)(this["FavInverter1"]));
            }
            set {
                this["FavInverter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint FavInverter2 {
            get {
                return ((uint)(this["FavInverter2"]));
            }
            set {
                this["FavInverter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint FavInverter3 {
            get {
                return ((uint)(this["FavInverter3"]));
            }
            set {
                this["FavInverter3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint FavInverter4 {
            get {
                return ((uint)(this["FavInverter4"]));
            }
            set {
                this["FavInverter4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint FavInverter5 {
            get {
                return ((uint)(this["FavInverter5"]));
            }
            set {
                this["FavInverter5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double InterspaceLength {
            get {
                return ((double)(this["InterspaceLength"]));
            }
            set {
                this["InterspaceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://classlesoft.in")]
        public string ReportCompWebsite {
            get {
                return ((string)(this["ReportCompWebsite"]));
            }
            set {
                this["ReportCompWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cologne, Germany")]
        public string ReportCompAddress {
            get {
                return ((string)(this["ReportCompAddress"]));
            }
            set {
                this["ReportCompAddress"] = value;
            }
        }
    }
}
